appdir: "{{ ansible_user_dir }}/spring"
branch: "main"
appuser: "{{ansible_user_id}}"
appgroup: "{{ansible_user_gid}}"
app_port: 8081
backend_server_url: "http://135.225.105.38:8081"
app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: myuser
    spring.datasource.password: pass12345
    spring.datasource.url: jdbc:postgresql://135.225.105.38:5433/mydb

