---
- name: install postgres
  hosts: dbservers
  become: yes
  become_user: root
 
  tasks:
    # Install PostgreSQL and pip for managing Python packages
    - name: install postgres  and pip packages
      apt:
        name: postgresql, python3-pip
        state: present
        update_cache: yes
      tags:
        - install

    # Only for Ubuntu 24.04: configure PostgreSQL to allow remote access
    - block:

        # Enable listening on all IP addresses in postgresql.conf
        - name: edit postgres.conf
          lineinfile:
            path: /etc/postgresql/16/main/postgresql.conf
            regexp: '^#listen_addresses ='
            line:  "listen_addresses='*'"
          notify:
            - restart postgres
          tags:
            - edit

        # Allow remote connections from any IP using md5 authentication
        - name: edit pg_hba.conf
          lineinfile:
            path: /etc/postgresql/16/main/pg_hba.conf
            line:  "host	all	all	0.0.0.0/0	md5"
            create: yes
          notify:
            - restart postgres
          tags:
            - edit

      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'



    # Attempt to create a user and database; handle failure gracefully
    - block:
        # Create a PostgreSQL user with password
        - name: create postgres user
          postgresql_user:
            name: myuser
            password: 'pass12345'
          become: yes
          become_user: postgres

        # Create a database owned by the new user
        - name: create postgres database
          postgresql_db:
            name: mydb
            owner: myuser
          become: yes
          become_user: postgres
      rescue:
        # - name: install python pg module
        #   command: pip3 install psycopg2-binary --break-system-packages
        #   tags:
        #     - install
        # If user/database creation fails (likely due to missing psycopg2), install psycopg2 via apt
        - name: apt install psycopg2-binary
          apt:
            name: python3-psycopg2
            state: present
          tags:
            - install

      always:
        # Ensure user creation is retried regardless of previous failure
        - name: create postgres user
          postgresql_user:
            name: myuser
            password: 'pass12345'
          become: yes
          become_user: postgres

          # Ensure database creation is retried regardless of previous failure
        - name: create postgres database
          postgresql_db:
            name: mydb
            owner: myuser
          become: yes
          become_user: postgres

  handlers:
    # Restart PostgreSQL service when notified by configuration changes
    - name: restart postgres
      service:
        name: postgresql
        state: restarted