app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: myuser
    spring.datasource.password: pass12345
    spring.datasource.url: jdbc:postgresql://135.225.105.38:5433/mydb

service:
  workingdir: "{{ ansible_user_dir }}/spring"
  execstart: "java -jar {{ ansible_user_dir }}/spring/target/rentEstate-0.0.1-SNAPSHOT.jar"
